### ISSUE TITLE
ClassNLLCriterion returns NaN when prediction is 0

### ISSUE THREAD

**Issue by sbereda** [lucasb-eyer/DeepFried2#82]
When a prediction for a specific class is 0, then ClassNLLCriterion returns NaN, since log(0)=NaN. I don't know whether that is the desired behaviour.

**Comment by lucasb-eyer** [comment]
yes it is. This should not matter when it's combined with softmax because theano automatically stabilizes it (should be described in the theano tutorials).
So my guess is you're not using softmax, but spatial softmax. In that case, use `algo='log'` and set the `ClassNLLCriterion`'s `log=False`. You can learn more about this by doing my AML exercise ;-)
